language: php

php:
  - 7.3

env:
  global:
    - PLUGIN_NAME=Example
    - REQUIRE=""
    - DB=mysql
    - CAKE_REF=2.x
    - PHPUNIT=5.7.19

services:
  - mysql

matrix:
  include:
    - php: 7.3
      env:
        - CODECOVERAGE=1
    - php: 7.3
      env:
        - PHPCS=1
    - php: 7.3
      env:
        - FOC_VALIDATE=1

before_script:
  - cp -R example_plugin ../example_plugin && cd ../example_plugin
  - ../travis/before_script.sh

script:
  - ../travis/script.sh

after_success:
  - ../travis/after_success.sh

notifications:
  email: false
